### ISSUE TITLE
Erro ao rodar o projeto

### ISSUE THREAD

**Issue by brunostefanni** [luiguild/map-visualization-e-big-data#2]
Depois de instalar as dependências foi rodar a aplicação e retornou esse erro:

> This relative module was not found:
> * ../../../static/json/layers-full.json in ./~/babel-loader/lib!./ ~/vue-loader/l
> ib/selector.js?type=script&index=0!./src/components/atoms/map.vue

no arquivo **src/components/atoms/map.vue** na linha 184 temos:
`const allLayers = require('../../../static/json/layers-full.json')`

não encontrei o arquivo **layers-full.json** no projeto.

**Comment by luiguild** [comment]
Fala @brunostefanni, esse arquivo infelizmente é privado, você pode simplesmente comentar essa importação e rodar o projeto sem ele... isso é uma api 'mockapeada' que recebe algumas url's de layers privados da empresa que trabalho... Valeu! 😃
